
* Status
** test0, test6, test6a, test7, test8, test9 working

* Design Intention
** FYI - when an event arrives at a Code part (aka Leaf), it runs some code (usually a CASE on the pin name) to completion then returns.  When an event arrives at a Schematic, the "same" thing happens - the event is passed into the bowels of the schematic and is processed to completion by the graph of parts.
** schematic input handler
   set self.busy true
   lookup the input pin in self.sources, then dispatch the event
   set self.busy false (the dispatcher will see self as busy recursively, if any of self's children are busy, this recurs until we hit code parts.  [nb. need to revamp busy to tak output and input queues into account in parts of lower-level schematics)


* Incoming vs Outgoing
** An Outgoing Receiver is one who's target is an output pin
** Everything else is Incoming (there is only one other direction :in)

* Todo examples
** character pipeline
** whole-file pipeline
** full-blown network (with feedback)
** do we need a line-based pipeline (i.e. unix-like)?


* branches
** master
<<<<<<< HEAD
** pt-20191117c-macro - wip for macro

* todo

